"""Reseed blinds table

Revision ID: 4898221d01bc
Revises: d8372f2e808a
Create Date: 2026-05-28 00:22:23.326706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4898221d01bc'
down_revision = 'd8372f2e808a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blinds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('blind_type', sa.Enum('SMALL', 'BIG', 'BOSS', 'SHOWDOWN', name='blind_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('ante', sa.String(length=20), nullable=True),
    sa.Column('score_multiplier', sa.Float(), nullable=True),
    sa.Column('reward_money', sa.SmallInteger(), nullable=True),
    sa.Column('matador_compatible', sa.Boolean(), nullable=False),
    sa.Column('wiki_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blinds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blinds_blind_type'), ['blind_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_blinds_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blinds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blinds_name'))
        batch_op.drop_index(batch_op.f('ix_blinds_blind_type'))

    op.drop_table('blinds')
    # ### end Alembic commands ###
