"""add Sticker reference model and user sticker tracking tables

Revision ID: 4ee5e683fb9c
Revises: 6f0cd1ed8336
Create Date: 2026-05-16 13:21:37.215909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee5e683fb9c'
down_revision = '6f0cd1ed8336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stickers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sticker_type', sa.Enum('IN_RUN', 'STAKE', name='sticker_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('stake_id', sa.Integer(), nullable=True),
    sa.Column('sticker_order', sa.SmallInteger(), nullable=False),
    sa.Column('wiki_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['stake_id'], ['stakes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stickers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stickers_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_stickers_sticker_order'), ['sticker_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_stickers_sticker_type'), ['sticker_type'], unique=False)

    op.create_table('user_deck_stickers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('highest_stake_order', sa.SmallInteger(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'STEAM_SYNC', name='unlock_source'), nullable=False),
    sa.CheckConstraint('highest_stake_order BETWEEN 1 AND 8', name='ck_user_deck_stickers_order_range'),
    sa.ForeignKeyConstraint(['deck_id'], ['unlockables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'deck_id')
    )
    op.create_table('user_joker_stickers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joker_id', sa.Integer(), nullable=False),
    sa.Column('highest_stake_order', sa.SmallInteger(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'STEAM_SYNC', name='unlock_source'), nullable=False),
    sa.CheckConstraint('highest_stake_order BETWEEN 1 AND 8', name='ck_user_joker_stickers_order_range'),
    sa.ForeignKeyConstraint(['joker_id'], ['unlockables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'joker_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_joker_stickers')
    op.drop_table('user_deck_stickers')
    with op.batch_alter_table('stickers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stickers_sticker_type'))
        batch_op.drop_index(batch_op.f('ix_stickers_sticker_order'))
        batch_op.drop_index(batch_op.f('ix_stickers_name'))

    op.drop_table('stickers')
    # ### end Alembic commands ###
