"""initial schema with users, unlockables, items and achievements

Revision ID: 66e6a8970e43
Revises: 
Create Date: 2026-05-07 23:06:24.982234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e6a8970e43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('steam_api_name', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_steam_api_name'), ['steam_api_name'], unique=True)

    op.create_table('unlockables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('JOKER', 'TAROT', 'PLANET', 'SPECTRAL', 'VOUCHER', 'DECK', name='unlockable_type'), nullable=False),
    sa.Column('item_number', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('unlock_condition', sa.String(length=500), nullable=True),
    sa.Column('wiki_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'item_number', name='uq_unlockables_type_number')
    )
    with op.batch_alter_table('unlockables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unlockables_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_unlockables_type'), ['type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('steam_id', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_steam_sync', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('firebase_uid IS NOT NULL OR steam_id IS NOT NULL', name='ck_user_has_identity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_steam_id'), ['steam_id'], unique=True)

    op.create_table('consumables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.SmallInteger(), nullable=True),
    sa.Column('sell_price', sa.SmallInteger(), nullable=True),
    sa.Column('in_shop', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['unlockables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumables_buy_price'), ['buy_price'], unique=False)

    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['unlockables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY', name='joker_rarity'), nullable=False),
    sa.Column('effect_type', sa.String(length=50), nullable=True),
    sa.Column('activation', sa.String(length=50), nullable=True),
    sa.Column('buy_price', sa.SmallInteger(), nullable=True),
    sa.Column('sell_price', sa.SmallInteger(), nullable=True),
    sa.Column('in_shop', sa.Boolean(), nullable=False),
    sa.Column('has_negative_variant', sa.Boolean(), nullable=False),
    sa.Column('negative_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_copyable', sa.Boolean(), nullable=False),
    sa.Column('is_perishable', sa.Boolean(), nullable=False),
    sa.Column('is_eternal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['unlockables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jokers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jokers_buy_price'), ['buy_price'], unique=False)
        batch_op.create_index(batch_op.f('ix_jokers_effect_type'), ['effect_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jokers_rarity'), ['rarity'], unique=False)

    op.create_table('user_achievements',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked', sa.Boolean(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'STEAM_SYNC', name='unlock_source'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    op.create_table('user_unlocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unlockable_id', sa.Integer(), nullable=False),
    sa.Column('unlocked', sa.Boolean(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'STEAM_SYNC', name='unlock_source'), nullable=False),
    sa.ForeignKeyConstraint(['unlockable_id'], ['unlockables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'unlockable_id', name='uq_user_unlocks_user_item')
    )
    with op.batch_alter_table('user_unlocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_unlocks_user_id'), ['user_id'], unique=False)

    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_tier', sa.Enum('BASE', 'UPGRADED', name='voucher_tier'), nullable=False),
    sa.Column('next_voucher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['unlockables.id'], ),
    sa.ForeignKeyConstraint(['next_voucher_id'], ['unlockables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vouchers_voucher_tier'), ['voucher_tier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vouchers_voucher_tier'))

    op.drop_table('vouchers')
    with op.batch_alter_table('user_unlocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_unlocks_user_id'))

    op.drop_table('user_unlocks')
    op.drop_table('user_achievements')
    with op.batch_alter_table('jokers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jokers_rarity'))
        batch_op.drop_index(batch_op.f('ix_jokers_effect_type'))
        batch_op.drop_index(batch_op.f('ix_jokers_buy_price'))

    op.drop_table('jokers')
    op.drop_table('decks')
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumables_buy_price'))

    op.drop_table('consumables')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_steam_id'))
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))

    op.drop_table('users')
    with op.batch_alter_table('unlockables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unlockables_type'))
        batch_op.drop_index(batch_op.f('ix_unlockables_name'))

    op.drop_table('unlockables')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_steam_api_name'))

    op.drop_table('achievements')
    # ### end Alembic commands ###
