"""add CardModifier reference model with ModifierType enum

Revision ID: 6f0cd1ed8336
Revises: 83afae5a0073
Create Date: 2026-05-16 12:05:07.143214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0cd1ed8336'
down_revision = '83afae5a0073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_modifiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('modifier_type', sa.Enum('ENHANCEMENT', 'EDITION', 'SEAL', name='modifier_type'), nullable=False),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('wiki_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_modifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_modifiers_modifier_type'), ['modifier_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_modifiers_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_modifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_modifiers_name'))
        batch_op.drop_index(batch_op.f('ix_card_modifiers_modifier_type'))

    op.drop_table('card_modifiers')
    # ### end Alembic commands ###
