"""add Stake, Blind, Tag reference models

Revision ID: 8792a1949c18
Revises: f8604dc40341
Create Date: 2026-05-11 21:16:05.004033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8792a1949c18'
down_revision = 'f8604dc40341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blinds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('blind_type', sa.Enum('SMALL', 'BIG', 'BOSS', name='blind_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('ante', sa.String(length=20), nullable=True),
    sa.Column('score_multiplier', sa.Float(), nullable=True),
    sa.Column('reward_money', sa.SmallInteger(), nullable=True),
    sa.Column('matador_compatible', sa.Boolean(), nullable=False),
    sa.Column('wiki_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blinds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blinds_blind_type'), ['blind_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_blinds_name'), ['name'], unique=True)

    op.create_table('stakes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('stake_order', sa.SmallInteger(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('effect_description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('unlocks_deck_name', sa.String(length=50), nullable=True),
    sa.Column('wiki_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stakes_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_stakes_stake_order'), ['stake_order'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('ante', sa.String(length=20), nullable=True),
    sa.Column('unlock_condition', sa.String(length=500), nullable=True),
    sa.Column('wiki_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    with op.batch_alter_table('stakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stakes_stake_order'))
        batch_op.drop_index(batch_op.f('ix_stakes_name'))

    op.drop_table('stakes')
    with op.batch_alter_table('blinds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blinds_name'))
        batch_op.drop_index(batch_op.f('ix_blinds_blind_type'))

    op.drop_table('blinds')
    # ### end Alembic commands ###
