"""Recrear UserStickerApplication con Dual-Source

Revision ID: d8372f2e808a
Revises: m2_unlock_factors
Create Date: 2026-05-27 20:03:30.291847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8372f2e808a'
down_revision = 'm2_unlock_factors'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sticker_applications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unlockable_id', sa.Integer(), nullable=False),
    sa.Column('manual_stake_order', sa.SmallInteger(), nullable=False),
    sa.Column('steam_stake_order', sa.SmallInteger(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('manual_stake_order BETWEEN 0 AND 8', name='ck_usa_manual_order'),
    sa.CheckConstraint('steam_stake_order BETWEEN 0 AND 8', name='ck_usa_steam_order'),
    sa.ForeignKeyConstraint(['unlockable_id'], ['unlockables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'unlockable_id')
    )
    with op.batch_alter_table('user_sticker_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sticker_applications_unlockable_id'), ['unlockable_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sticker_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sticker_applications_unlockable_id'))

    op.drop_table('user_sticker_applications')
    # ### end Alembic commands ###
