"""add PokerHand reference model

Revision ID: f8604dc40341
Revises: ec117fc0b7ea
Create Date: 2026-05-10 18:54:30.842685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8604dc40341'
down_revision = 'ec117fc0b7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poker_hands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('base_chips', sa.SmallInteger(), nullable=False),
    sa.Column('base_mult', sa.SmallInteger(), nullable=False),
    sa.Column('chips_per_level', sa.SmallInteger(), nullable=False),
    sa.Column('mult_per_level', sa.SmallInteger(), nullable=False),
    sa.Column('planet_card_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('hand_order', sa.SmallInteger(), nullable=False),
    sa.Column('wiki_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poker_hands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poker_hands_hand_order'), ['hand_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_poker_hands_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poker_hands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poker_hands_name'))
        batch_op.drop_index(batch_op.f('ix_poker_hands_hand_order'))

    op.drop_table('poker_hands')
    # ### end Alembic commands ###
